# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookstore2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import mysql.connector as mc
from login import *


class Bookstore(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1127, 756)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1131, 151))
        self.frame.setStyleSheet("background-color: \"green\"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 1111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setGeometry(QtCore.QRect(960, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-color: \"grey\"")
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.login)

        self.cartButton = QtWidgets.QPushButton(self.frame)
        self.cartButton.setGeometry(QtCore.QRect(40, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cartButton.setFont(font)
        self.cartButton.setStyleSheet("background-color: \"red\"")
        self.cartButton.setObjectName("cartButton")

        self.favouriteButton = QtWidgets.QPushButton(self.frame)
        self.favouriteButton.setGeometry(QtCore.QRect(40, 80, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.favouriteButton.setFont(font)
        self.favouriteButton.setStyleSheet("background-color:  rgb(173,216,230)")
        self.favouriteButton.setObjectName("favouriteButton")
        self.searchEdit = QtWidgets.QLineEdit(self.frame)
        self.searchEdit.setGeometry(QtCore.QRect(430, 70, 281, 31))
        self.searchEdit.setStyleSheet("background-color: white;")
        self.searchEdit.setObjectName("searchEdit")
        self.searchButton = QtWidgets.QPushButton(self.frame)
        self.searchButton.setGeometry(QtCore.QRect(520, 110, 111, 23))
        self.searchButton.setStyleSheet("background-color: grey;")
        self.searchButton.setObjectName("searchButton")
        self.searchButton.clicked.connect(self.search)

        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(250, 180, 711, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.addToFavButton = QtWidgets.QPushButton(Form)
        self.addToFavButton.setGeometry(QtCore.QRect(680, 640, 141, 41))
        self.addToFavButton.setStyleSheet("background-color:  rgb(173,216,230)")
        self.addToFavButton.setObjectName("addToFavButton")
        self.addToFavButton.clicked.connect(self.insertData)

        self.addToCartButton = QtWidgets.QPushButton(Form)
        self.addToCartButton.setGeometry(QtCore.QRect(430, 640, 141, 41))
        self.addToCartButton.setStyleSheet("background-color: \"red\"")
        self.addToCartButton.setObjectName("addToCartButton")
        self.tableWidget.setColumnWidth(0, 608)
        self.tableWidget.setColumnWidth(1, 100)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "BOOKSTORE SMART"))
        self.loginButton.setText(_translate("Form", "Login"))
        self.cartButton.setText(_translate("Form", "Cart"))
        self.favouriteButton.setText(_translate("Form", "Favourites"))
        self.searchButton.setText(_translate("Form", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Title"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Price"))
        self.addToFavButton.setText(_translate("Form", "Add to favourite"))
        self.addToCartButton.setText(_translate("Form", "Add to cart"))

    def search(self):
        global book
        response = requests.get("https://api.itbook.store/1.0/search/" + self.searchEdit.text())
        book = response.json()['books']
        self.loadData()

    def loadData(self):
        row = 0
        self.tableWidget.setRowCount(len(book))
        for books in range(len(book)):
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(book[books]['title']))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(book[books]['price']))
            row=row+1

    def login(self):
        self.window = QtWidgets.QWidget()
        self.ui = Login()
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    Form = QtWidgets.QWidget()
    ui = Bookstore()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
