# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Cart(object):
    def setupUi(self, Cart):
        Cart.setObjectName("Cart")
        Cart.resize(764, 610)
        self.tableWidget = QtWidgets.QTableWidget(Cart)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 721, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.checkout = QtWidgets.QPushButton(Cart)
        self.checkout.setGeometry(QtCore.QRect(580, 540, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkout.setFont(font)
        self.checkout.setStyleSheet("background-color: \"grey\"")
        self.checkout.setObjectName("checkout")
        self.checkout.clicked.connect(self.total)
        self.frame = QtWidgets.QFrame(Cart)
        self.frame.setGeometry(QtCore.QRect(-190, 0, 1131, 71))
        self.frame.setStyleSheet("background-color: \"green\"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 1111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.refresh = QtWidgets.QPushButton(Cart)
        self.refresh.setGeometry(QtCore.QRect(200, 540, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refresh.setFont(font)
        self.refresh.setStyleSheet("background-color: \"lightblue\"")
        self.refresh.setObjectName("refresh")
        self.refresh.clicked.connect(self.getData)

        self.removeItem = QtWidgets.QPushButton(Cart)
        self.removeItem.setGeometry(QtCore.QRect(20, 540, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeItem.setFont(font)
        self.removeItem.setStyleSheet("background-color: \"red\"")
        self.removeItem.setObjectName("removeItem")
        self.removeItem.clicked.connect(self.removeBook)
        self.totalPrice = QtWidgets.QLabel(Cart)
        self.totalPrice.setGeometry(QtCore.QRect(360, 540, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.totalPrice.setFont(font)
        self.totalPrice.setText("")
        self.totalPrice.setObjectName("totalPrice")

        self.tableWidget.setColumnWidth(0, 608)
        self.tableWidget.setColumnWidth(1, 100)

        self.retranslateUi(Cart)
        QtCore.QMetaObject.connectSlotsByName(Cart)

    def retranslateUi(self, Cart):
        _translate = QtCore.QCoreApplication.translate
        Cart.setWindowTitle(_translate("Cart", "Cart"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Cart", "Title"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Cart", "Price"))
        self.checkout.setText(_translate("Cart", "CHECKOUT"))
        self.label.setText(_translate("Cart", "CART"))
        self.refresh.setText(_translate("Cart", "REFRESH"))
        self.removeItem.setText(_translate("Cart", "REMOVE ITEM"))

    def total(self):
        price = [self.tableWidget.item(row, 1).text() for row in range (self.tableWidget.rowCount())]
        print(price)

    def getData(self):

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="bookstore"
        )

        mycursor = mydb.cursor()
        mycursor.execute("SELECT title, price from cart")
        result = mycursor.fetchall()

        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))

    def removeBook(self):

        row = self.tableWidget.currentRow()

        currentTitle = (self.tableWidget.item(row, 0).text())
        currentPrice = (self.tableWidget.item(row, 1).text())

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="bookstore"
        )
        mycursor = mydb.cursor()
        mycursor.execute("DELETE FROM cart WHERE title like '" + currentTitle + "' and price like '" + currentPrice +"'")
        mydb.commit()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cart = QtWidgets.QWidget()
    ui = Ui_Cart()
    ui.setupUi(Cart)
    Cart.show()
    sys.exit(app.exec_())
