# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(509, 391)
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(0, 0, 511, 81))
        self.frame.setStyleSheet("background-color: \"green\"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, -1, 511, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.emailEdit = QtWidgets.QLineEdit(Login)
        self.emailEdit.setGeometry(QtCore.QRect(90, 110, 401, 22))
        self.emailEdit.setObjectName("emailEdit")
        self.passwordEdit = QtWidgets.QLineEdit(Login)
        self.passwordEdit.setGeometry(QtCore.QRect(90, 160, 401, 22))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 111, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 101, 20))
        self.label_3.setObjectName("label_3")
        self.loginButton = QtWidgets.QPushButton(Login)
        self.loginButton.setGeometry(QtCore.QRect(250, 260, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.login)
        self.resultLabel = QtWidgets.QLabel(Login)
        self.resultLabel.setGeometry(QtCore.QRect(10, 260, 181, 101))
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Login"))
        self.label_2.setText(_translate("Login", "E - mail"))
        self.label_3.setText(_translate("Login", "Password"))
        self.loginButton.setText(_translate("Login", "Login"))


    def login(self):
        try:
            email = self.emailEdit.text()
            password = self.passwordEdit.text()

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="bookstore"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT email,password from users where email like '"+email + "'and password like '"+password+"'")
            result = mycursor.fetchone()

            if result == None:
                self.resultLabel.setStyleSheet("color: red")
                self.resultLabel.setText("Login Failed")

            else:
                self.resultLabel.setStyleSheet("color: green")
                self.resultLabel.setText("Login successful")

        except mc.Error as e:
            self.resultLabel.setText("Error")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
