# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(508, 389)
        self.label = QtWidgets.QLabel(SignUp)
        self.label.setGeometry(QtCore.QRect(0, 0, 511, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:\"green\"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SignUp)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 111, 20))
        self.label_2.setObjectName("label_2")
        self.emailEdit = QtWidgets.QLineEdit(SignUp)
        self.emailEdit.setGeometry(QtCore.QRect(90, 100, 401, 22))
        self.emailEdit.setObjectName("emailEdit")
        self.passwordEdit = QtWidgets.QLineEdit(SignUp)
        self.passwordEdit.setGeometry(QtCore.QRect(90, 140, 401, 22))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.label_3 = QtWidgets.QLabel(SignUp)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 101, 20))
        self.label_3.setObjectName("label_3")
        self.fornameEdit = QtWidgets.QLineEdit(SignUp)
        self.fornameEdit.setGeometry(QtCore.QRect(90, 180, 401, 22))
        self.fornameEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fornameEdit.setObjectName("fornameEdit")
        self.label_4 = QtWidgets.QLabel(SignUp)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 101, 20))
        self.label_4.setObjectName("label_4")
        self.surnameEdit = QtWidgets.QLineEdit(SignUp)
        self.surnameEdit.setGeometry(QtCore.QRect(90, 220, 401, 22))
        self.surnameEdit.setText("")
        self.surnameEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.surnameEdit.setObjectName("surnameEdit")
        self.label_5 = QtWidgets.QLabel(SignUp)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 101, 20))
        self.label_5.setObjectName("label_5")
        self.signUpButton = QtWidgets.QPushButton(SignUp)
        self.signUpButton.setGeometry(QtCore.QRect(250, 260, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.signUpButton.setFont(font)
        self.signUpButton.setObjectName("signUpButton")
        self.signUpButton.clicked.connect(self.createAcc)
        self.resultLabel = QtWidgets.QLabel(SignUp)
        self.resultLabel.setGeometry(QtCore.QRect(20, 260, 181, 101))
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "Create Account"))
        self.label.setText(_translate("SignUp", "Create Account"))
        self.label_2.setText(_translate("SignUp", "E - mail"))
        self.label_3.setText(_translate("SignUp", "Password"))
        self.label_4.setText(_translate("SignUp", "Forname"))
        self.label_5.setText(_translate("SignUp", "Surname"))
        self.signUpButton.setText(_translate("SignUp", "Sign Up"))

    def createAcc(self):
            email = self.emailEdit.text()
            forname = self.fornameEdit.text()
            surname = self.surnameEdit.text()
            password = self.passwordEdit.text()

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="bookstore"
            )


            mycursor = mydb.cursor()
            mycursor.execute("SELECT email from users where email like'"+email+"'")
            result = mycursor.fetchone()

            if result is not None:
                self.resultLabel.setStyleSheet("color: red")
                self.resultLabel.setText("User already exists")
            else:
                sql = "INSERT INTO users (email, forname, surname, password) VALUES (%s, %s, %s, %s)"
                val = (email, forname, surname, password)
                mycursor.execute(sql, val)
                mydb.commit()
                self.resultLabel.setStyleSheet("color: green")
                self.resultLabel.setText("User created")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUp = QtWidgets.QWidget()
    ui = Ui_SignUp()
    ui.setupUi(SignUp)
    SignUp.show()
    sys.exit(app.exec_())
