# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class SignUp(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 71))
        self.frame.setStyleSheet("background-color: green;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.surnameEdit = QtWidgets.QLineEdit(Form)
        self.surnameEdit.setGeometry(QtCore.QRect(80, 150, 301, 21))
        self.surnameEdit.setObjectName("surnameEdit")
        self.forenameEdit = QtWidgets.QLineEdit(Form)
        self.forenameEdit.setGeometry(QtCore.QRect(80, 120, 301, 21))
        self.forenameEdit.setObjectName("forenameEdit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 51, 21))
        self.label_4.setObjectName("label_4")
        self.emailEdit = QtWidgets.QLineEdit(Form)
        self.emailEdit.setGeometry(QtCore.QRect(80, 90, 301, 21))
        self.emailEdit.setObjectName("emailEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 51, 21))
        self.label_2.setObjectName("label_2")
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setGeometry(QtCore.QRect(80, 180, 301, 21))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 51, 21))
        self.label_5.setObjectName("label_5")
        self.createAccButton = QtWidgets.QPushButton(Form)
        self.createAccButton.setGeometry(QtCore.QRect(270, 220, 111, 51))
        self.createAccButton.setObjectName("createAccButton")
        self.createAccButton.clicked.connect(self.signUp)
        self.resultLabel = QtWidgets.QLabel(Form)
        self.resultLabel.setGeometry(QtCore.QRect(10, 220, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setStyleSheet("color: red")
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Create account"))
        self.label_4.setText(_translate("Form", "Surname:"))
        self.label_3.setText(_translate("Form", "Forename"))
        self.label_2.setText(_translate("Form", "E-mail:"))
        self.label_5.setText(_translate("Form", "Password:"))
        self.createAccButton.setText(_translate("Form", "Create"))

    def signUp(self):
        email = self.emailEdit.text()
        forename = self.forenameEdit.text()
        surname = self.surnameEdit.text()
        password = self.passwordEdit.text()

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="bookstore"
        )

        mycursor = mydb.cursor()
        mycursor.execute("SELECT email from users where email like'" + email + "'")
        result = mycursor.fetchone()

        if result is not None:
            self.resultLabel.setStyleSheet("color: red")
            self.resultLabel.setText("User already exists")
        else:
            sql = "INSERT INTO users (email, forename, surname, password) VALUES (%s, %s, %s, %s)"
            val = (email, forename, surname, password)
            mycursor.execute(sql, val)
            mydb.commit()
            self.resultLabel.setStyleSheet("color: green")
            self.resultLabel.setText("User created")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    Form = QtWidgets.QWidget()
    ui = SignUp()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
